version: "3.8"

services:
    db:
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        image: postgres:13.3-alpine
        volumes:
            - ${HOME}/postgres-data/:/var/lib/postgresql/data
        ports:
            - 5432:5432

    app:
        depends_on:
            - db
        build: .
        environment:
            DATABASE: "postgres"
            DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
            AUTHORITY: "${AUTHORITY}"
            RUST_BACKTRACE: 1
            RUST_LOG: "acitx_web=info,actix_server=info"
            SERVER: "0.0.0.0:8080"
        ports:
            - 8080:8080

volumes:
    postgres-data: