version: "3.8"

services:
    db:
        # .env from project base is automatically read (+v1.28)
        environment:
            POSTGRES_USER: "${DB_USER}"
            POSTGRES_DB: "${DB_NAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
        image: postgres:13.3-alpine
        volumes:
            - ${HOME}/postgres-data/:/var/lib/postgresql/data
        ports:
            - 5432:5432

    app:
        depends_on:
            - db
        build: .
        # .env can also be specified directly (ie. .env.local)
        env_file:
            - .env
        ports:
            - 8080:8080

volumes:
    postgres-data: