version: 2

jobs:
    checkout_and_bundle_dependencies:
        docker:
            - image: circleci/postgres:alpine
            - image: clux/muslrust
        auth:
            username: $DOCKERHUB_USER
            password: $DOCKERHUB_PASSWORD
        working_directory: /volume
        steps:
            - checkout
            - restore_cache:
                keys:
                    - target-bundle-{{ checksum "Cargo.toml" }}
                    - target-bundle-
            - run: cargo build --release
            - save_cache:
                key: target-bundle-{{ checksum "Cargo.toml" }}
                paths:
                    - target

workflows:
    version: 2
    build-and-deploy-soon:
        jobs:
            - checkout_and_bundle_dependencies:
                context:
                    - docker-hub-creds
