# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2

jobs:
    checkout_and_bundle_dependencies:
        docker:
            - image: cimg/rust:1.52.1
            - image: circleci/postgres:alpine
        working_directory: /volume
        steps:
            - checkout
            - run: echo 'export CACHE_VERSION="1"' >> $BASH_ENV
            - restore_cache:
                key: cargo.registry-{{ .Environment.CACHE_VERSION }}
            - restore_cache:
                key: target.release-{{ .Environment.CACHE_VERSION }}
            - run: cargo install diesel_cli --no-default-features --features postgres
            - run: cargo build --release
            - save_cache:
                key: target.release-{{ .Environment.CACHE_VERSION }}
                paths:
                    - target
            - save_cache:
                key: cargo.registry-{{ .Environment.CACHE_VERSION }}
                paths:
                    - /root/.cargo
            - persist_to_workspace:
                root: target/release/
                paths:
                    - backend-rs

workflows:
    version: 2
    build-and-deploy-soon:
        jobs:
            - checkout_and_bundle_dependencies
