version: 2

jobs:
    build_and_test:
        docker:
            - image: clux/muslrust
              auth:
                  username: $DOCKERHUB_USER
                  password: $DOCKERHUB_PASSWORD
              working_directory: /volume
              environment:
                  DATABASE_URL: $DATABASE_URL

            - image: circleci/postgres:9.6.5-alpine-ram
              environment:
                  POSTGRES_USER: $POSTGRES_USER
                  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
                  POSTGRES_DB: $POSTGRES_DB

        steps:
            - checkout
            - restore_cache:
                  keys:
                      - target-bundle-{{ checksum "Cargo.toml" }}
                      - target-bundle-
            - run: cargo test
            - save_cache:
                  key: target-bundle-{{ checksum "Cargo.toml" }}
                  paths:
                      - target

workflows:
    version: 2
    build-test-and-deploy:
        jobs:
            - build_and_test:
                  context:
                      - docker-hub-creds
                      - postgres-creds
                      - env-vars
